### ISSUE TITLE
SMPLer-X and SynBody

### ISSUE THREAD

**Issue by caizhongang** [tinatiansjz/hmr-survey#3]
Thank you for the wonderful survey! It is especially inspiring to know that the survey is continuously updated.

We have two recent works that might be interesting to the community:
- [**SMPLer-X: Scaling Up Expressive Human Pose and Shape Estimation (NeurIPS'23, D&B Track)**](https://caizhongang.github.io/projects/SMPLer-X/)
- [**SynBody: Synthetic Dataset with Layered Human Models for 3D Human Perception and Modeling (ICCV'23)**](https://synbody.github.io/)

We would really appreciate it if you could add them in your survey! Let me know your thoughts :)

**Comment by HongwenZhang** [comment]
Hi Zhongang, Congratulations on your recent work! 

Both SMPLer-X and SynBody are important benchmark methods/datasets to the community. We are pleased to include them in the tables of our survey :)

Besides, I have created [an issue](https://github.com/tinatiansjz/hmr-survey/issues/4) to collect more recent work that appeared in ICCV'23 and NeurIPS'23. The arXiv version of our survey is about to be updated at the end of this year.

Thank you!

**Comment by caizhongang** [comment]
Really glad to know that, thank you!

**Comment by HongwenZhang** [comment]
Dear @caizhongang, it is just a friendly reminder that our survey paper has been updated at [arXiv](https://arxiv.org/abs/2203.01923). The updated papers can be also found in issue #4. Thank you! :)

**Comment by caizhongang** [comment]
Noted with thanks! @HongwenZhang
